### ISSUE TITLE
Adding Open Source Science panel from Nov2022 for the RA before Chelle

### ISSUE THREAD

**Issue by facusapienza21** [UCB-stat-159-s23/site#5]
I was thinking it will be useful to add the panel conversation as part of the reading assignments due the week before Chelle's lecture on 03/06. The video can be found in this [link](https://data.berkeley.edu/news/national-global-momentum-show-its-time-open-science-action-experts-say). Since the video is ~1.5hrs. I was thinking in removing one of the reading assignments due the same date. I think a good collection could be

- [Gentemann et al. 2021, Science Storms the Cloud](https://www.essoar.org/doi/10.1002/essoar.10506344.2).
- Gentemann et al. “[Satellite sea surface temperatures along the West Coast of the United States during the 2014–2016 northeast Pacific marine heat wave.](https://agupubs.onlinelibrary.wiley.com/doi/10.1002/2016GL071039)”.  We need this one for HW03. 
- Video with the panel discussion

This will leave outside [Perspectives on Data Reproducibility and Replicability in Paleoclimate and Climate Science](https://hdsr.mitpress.mit.edu/pub/dijwtzza/release/1). What do you think @fperez ?

**Comment by facusapienza21** [comment]
Approved.

**Comment by fperez** [comment]
Confirming, many tahnks @facusapienza21, please go ahead. You can tag the PR that makes this change with `Closes #5` and Github will automatically close it when merged.

**Comment by facusapienza21** [comment]
Oh sorry, I just saw this right after making the push to the main repository. I will keep it in mind for the next time! 

Since this was a small change, I didn't open a PR and directly just push to the main repo.

**Comment by fperez** [comment]
NP - you can also put the `Closes #5` comment directly in a commit. The nice thing about that is that it will both auto-close the issue, and create a reference link in the issue pointing to exactly what commit/PR did the fix :)
